    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.base.articolo.ArticoloCliente', 'it.dnd.thip.base.articolo.YArticoloCliente', '0', 'Y');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.base.articolo.ArticoloClienteTM', 'it.dnd.thip.base.articolo.YArticoloClienteTM', '0', 'Y');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('ArticoloCliente', 'YArticoloCliente', '1', 'Y');
