    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.logis.fis.Ubicazione', 'it.dnd.thip.logis.fis.YUbicazione', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.logis.fis.UbicazioneTM', 'it.dnd.thip.logis.fis.YUbicazioneTM', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('L_Ubicazione', 'YUbicazione', '1', 'N');
