# Class path : com.thera.thermfw.util.Replacement
# Class name : REPLACEMENT
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.vendite.documentoVE.web.DocumentoVenditaEstrattoFormModifier', 'it.dnd.thip.vendite.documentoVE.web.YDocumentoVenditaEstrattoFormModifier', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.vendite.documentoVE.web.DocumentoVenditaGridActionAdapter', 'it.dnd.thip.vendite.documentoVE.web.YDocumentoVenditaGridActionAdapter', '0', 'N');
	INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.vendite.documentoVE.web.DocumentoTestataVenditaEstrattoFormActionAdapter', 'it.dnd.thip.vendite.documentoVE.web.YDocumentoTestataVenditaEstrattoFormActionAdapter', '0', 'N');
