# Class path : com.thera.thermfw.util.Replacement
# Class name : REPLACEMENT
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.logis.fis.EsecuzioneMissioni', 'it.dnd.thip.logis.fis.YEsecuzioneMissioni', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.produzione.raccoltaDati.web.RilevDatiPrdTSFormActionAdapter', 'it.dnd.thip.produzione.raccoltaDati.web.YRilevDatiPrdTSFormActionAdapter', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.produzione.raccoltaDati.web.RilevDatiPrdTSWebFormModifier', 'it.dnd.thip.produzione.raccoltaDati.web.YRilevDatiPrdTSWebFormModifier', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it/thera/thip/produzione/raccoltaDati/NuovaDichiarazione.js', 'it/dnd/thip/produzione/raccoltaDati/YNuovaDichiarazione.js', '2', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it/thera/thip/produzione/raccoltaDati/ThipPersRilevContBtnPunto06.jsp', 'it/dnd/thip/produzione/raccoltaDati/YThipPersRilevContBtnPunto06.jsp', '2', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.base.azienda.Reparto', 'it.dnd.thip.base.azienda.YReparto', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.base.azienda.RepartoTM', 'it.dnd.thip.base.azienda.YRepartoTM', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('Reparto', 'YReparto', '1', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.logis.fis.Ubicazione', 'it.dnd.thip.logis.fis.YUbicazione', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.logis.fis.UbicazioneTM', 'it.dnd.thip.logis.fis.YUbicazioneTM', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('L_Ubicazione', 'YUbicazione', '1', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it/thera/thip/produzione/raccoltaDati/DichiarazioneConBolla.js', 'it/dnd/thip/produzione/raccoltaDati/YDichiarazioneConBolla.js', '2', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it/thera/thip/produzione/raccoltaDati/DichiarazioneConBollaInizRep.js', 'it/dnd/thip/produzione/raccoltaDati/YDichiarazioneConBollaInizRep.js', '2', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it/thera/thip/produzione/raccoltaDati/DichiarazioneConBollaSospFine.js', 'it/dnd/thip/produzione/raccoltaDati/YDichiarazioneConBollaSospFine.js', '2', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it/thera/thip/produzione/raccoltaDati/DichiarazioneMonitor.js', 'it/dnd/thip/produzione/raccoltaDati/YDichiarazioneMonitor.js', '2', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it/thera/thip/produzione/raccoltaDati/DichiarazionePrelievi.js', 'it/dnd/thip/produzione/raccoltaDati/YDichiarazionePrelievi.js', '2', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it/thera/thip/produzione/raccoltaDati/DichiarazioneRidotta.js', 'it/dnd/thip/produzione/raccoltaDati/YDichiarazioneRidotta.js', '2', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it/thera/thip/produzione/raccoltaDati/DichiarazioneRidottaNonProd.js', 'it/dnd/thip/produzione/raccoltaDati/YDichiarazioneRidottaNonProd.js', '2', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it/thera/thip/produzione/raccoltaDati/DichiarazioneSenzaBolla.js', 'it/dnd/thip/produzione/raccoltaDati/YDichiarazioneSenzaBolla.js', '2', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it/thera/thip/produzione/raccoltaDati/DichiarazioneSenzaBollaInizRep.js', 'it/dnd/thip/produzione/raccoltaDati/YDichiarazioneSenzaBollaInizRep.js', '2', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it/thera/thip/produzione/raccoltaDati/DichiarazioneSenzaBollaSospFine.js', 'it/dnd/thip/produzione/raccoltaDati/YDichiarazioneSenzaBollaSospFine.js', '2', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it/thera/thip/produzione/raccoltaDati/DichiarazioneVersamenti.js', 'it/dnd/thip/produzione/raccoltaDati/YDichiarazioneVersamenti.js', '2', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it/thera/thip/produzione/raccoltaDati/StampaBollaJSP.js', 'it/dnd/thip/produzione/raccoltaDati/YStampaBollaJSP.js', '2', 'N');
