# Class path : com.thera.thermfw.util.Replacement
# Class name : REPLACEMENT
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.logis.fis.EsecuzioneMissioni', 'it.dnd.thip.logis.fis.YEsecuzioneMissioni', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.produzione.raccoltaDati.web.RilevDatiPrdTSFormActionAdapter', 'it.dnd.thip.produzione.raccoltaDati.web.YRilevDatiPrdTSFormActionAdapter', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.produzione.raccoltaDati.web.RilevDatiPrdTSWebFormModifier', 'it.dnd.thip.produzione.raccoltaDati.web.YRilevDatiPrdTSWebFormModifier', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it/thera/thip/produzione/raccoltaDati/NuovaDichiarazione.js', 'it/dnd/thip/produzione/raccoltaDati/YNuovaDichiarazione.js', '2', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it/thera/thip/produzione/raccoltaDati/ThipPersRilevContBtnPunto06.jsp', 'it/dnd/thip/produzione/raccoltaDati/YThipPersRilevContBtnPunto06.jsp', '2', 'N');
