    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.base.azienda.Reparto', 'it.dnd.thip.base.azienda.YReparto', '0', 'Y');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.base.azienda.RepartoTM', 'it.dnd.thip.base.azienda.YRepartoTM', '0', 'Y');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('Reparto', 'YReparto', '1', 'Y');
