    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.base.generale.CfgLogTxMov', 'it.dnd.thip.base.generale.YCfgLogTxMov', '0', 'Y');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.base.generale.CfgLogTxMovTM', 'it.dnd.thip.base.generale.YCfgLogTxMovTM', '0', 'Y');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('CfgLogTxMov', 'YCfgLogTxMov', '1', 'Y');
